apiVersion: v1
baseDomain: labfun.org
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform:
    aws:
      type: m6i.xlarge
  replicas: 1
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform:
    aws:
      type: m6i.2xlarge
  replicas: 1
metadata:
  name: studentN
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: us-west-1
publish: External
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfYjliMThkNzU2YmRlNDJiMTg0ODY1MTljMjk4YWM1NmU6RTlSTzQ3MVI4VDk0OVY4MllaOEJCVjUwTElJTlZQT0JQTlhTRjBUWFlLQk9QMTlaR0Y5VDhaMlJQQUtUNlNRSQ==","email":"jason@innovationinsoftware.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfYjliMThkNzU2YmRlNDJiMTg0ODY1MTljMjk4YWM1NmU6RTlSTzQ3MVI4VDk0OVY4MllaOEJCVjUwTElJTlZQT0JQTlhTRjBUWFlLQk9QMTlaR0Y5VDhaMlJQQUtUNlNRSQ==","email":"jason@innovationinsoftware.com"},"registry.connect.redhat.com":{"auth":"fHVoYy1wb29sLWE1YjFlMmIyLTZjM2MtNGIyYy1hMGZlLWE5ZGJlYTI2YmEyNzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTRNMk5oWVdSbE5qRTVaamswWmpBeU9EVXpaRGd6TURrek4yWTJOREl3TlNKOS5PSHdQWGVXQUpCLXVMRld2N0M4U1dKLXJnYkRhVHM5UlZ1SlFtdjNmNXM0OUJFWUZ4bU9zYTNDM1ZvVWFkN3B4QmxwaTJZcnhlUHFrcVY0cEJ2aGE4bVMtN2RGei11bEZ3dGY0Q01UVWxjY1JjSlQ5QXZRT25iTENsc05PVlFBSDRlMHIyRHdSd3RlR0lFX01EUkRoVzhMaHFvOEIwdVB5b3pPNlRSYXQxeUpCNFVDSlNTOWdOaDMyaUhKdnRab3YyNGJrQ256YmhQZWJMRGhCdDY5c1dzSkVtaWNjRTJBYlVpUEhlUGZkUUFhOEMxUWF1Y3FXNWc0Q0JMSzdVS3lUR2RTZTZIM3laNjIwT1MwQ3B1MXdYajdvWmgxNHRJRGNlQmF6ckRHTl9DNTVJREl4X3NqclZqR212a3VNOEk5eEFOYTZuaGZmZEVaRW9OYW5NOXZGaURFOGhkZjdpY0wyNi1rRU5oRHo4M0puTWZsd19sZnJZZGpNSDNiRXF3Rm41eVo5Z0Y1Z3lMVmJtVm9YSzVENTBCNEl6T1VITmpoOExyemxyaEYtZG42S1RTcDVUZ0drX3NIUlg5ZGlpN1BRY2h0c2ZpQ1ZoUjA5dG5PcDU3aUc0M3NVYzNQSklNcW00OWJyRjEzQTNFZGIyaF9SOU1yallSM01lNmlJb181UHU3WFNsbDg5eHdzdC12eUp3ejhTNXVHcVJfbkxsSE9nOW11LU9VX0VKU056V0pCSy1oNHk0T0dfaXhrTU5iQUpjN1BreGxvZHBsWVR0QnUyTnF2ekZfWC1STkR3cmctbTBlWVNHS1NsWmJ5dUpiUnhycFhnYlRybHQzRFEwSzdxS25pRzZLbDJpelZEQXhZclZycjg3SWljRzJuaks5LTZweEk5b1VkRlNzWQ==","email":"jason@innovationinsoftware.com"},"registry.redhat.io":{"auth":"fHVoYy1wb29sLWE1YjFlMmIyLTZjM2MtNGIyYy1hMGZlLWE5ZGJlYTI2YmEyNzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTRNMk5oWVdSbE5qRTVaamswWmpBeU9EVXpaRGd6TURrek4yWTJOREl3TlNKOS5PSHdQWGVXQUpCLXVMRld2N0M4U1dKLXJnYkRhVHM5UlZ1SlFtdjNmNXM0OUJFWUZ4bU9zYTNDM1ZvVWFkN3B4QmxwaTJZcnhlUHFrcVY0cEJ2aGE4bVMtN2RGei11bEZ3dGY0Q01UVWxjY1JjSlQ5QXZRT25iTENsc05PVlFBSDRlMHIyRHdSd3RlR0lFX01EUkRoVzhMaHFvOEIwdVB5b3pPNlRSYXQxeUpCNFVDSlNTOWdOaDMyaUhKdnRab3YyNGJrQ256YmhQZWJMRGhCdDY5c1dzSkVtaWNjRTJBYlVpUEhlUGZkUUFhOEMxUWF1Y3FXNWc0Q0JMSzdVS3lUR2RTZTZIM3laNjIwT1MwQ3B1MXdYajdvWmgxNHRJRGNlQmF6ckRHTl9DNTVJREl4X3NqclZqR212a3VNOEk5eEFOYTZuaGZmZEVaRW9OYW5NOXZGaURFOGhkZjdpY0wyNi1rRU5oRHo4M0puTWZsd19sZnJZZGpNSDNiRXF3Rm41eVo5Z0Y1Z3lMVmJtVm9YSzVENTBCNEl6T1VITmpoOExyemxyaEYtZG42S1RTcDVUZ0drX3NIUlg5ZGlpN1BRY2h0c2ZpQ1ZoUjA5dG5PcDU3aUc0M3NVYzNQSklNcW00OWJyRjEzQTNFZGIyaF9SOU1yallSM01lNmlJb181UHU3WFNsbDg5eHdzdC12eUp3ejhTNXVHcVJfbkxsSE9nOW11LU9VX0VKU056V0pCSy1oNHk0T0dfaXhrTU5iQUpjN1BreGxvZHBsWVR0QnUyTnF2ekZfWC1STkR3cmctbTBlWVNHS1NsWmJ5dUpiUnhycFhnYlRybHQzRFEwSzdxS25pRzZLbDJpelZEQXhZclZycjg3SWljRzJuaks5LTZweEk5b1VkRlNzWQ==","email":"jason@innovationinsoftware.com"}}}'
sshKey: 'YOURSSHKEY'
